New Salesforce template
FrendsPlatform/FrendsTemplates pull request #76
Opened 2024-05-28 12:23 UTC by FrendsSarlinS

#59

2024-05-31 11:37 UTC, jannejjj commented
1. In the first exclusive decision of the process, where it is checked whether or not the input server address is empty, we should use `String.IsNullOrEmpty(#var.InServerAddress)` instead of `#var.InServerAddress == null`, since at least in my tests, the result was false and the process was trying to get the input file from the SFTP server, even with an empty adress.

2. In the exclusive decision where we check if the SFTP file was read succesfully, `string` is written with a lowercase s - it should be uppercase :D

3. From inside the for-loops, we could use intermediate returns instead of throwing errors, so that the whole process doesn't stop if there is an error inside one of the iterations

2024-06-03 07:00 UTC, FrendsSarlinS commented
Thanks for the comment, jannejjj! Changes were made according to your points in the comment.

2024-06-05 08:17 UTC, jefim requested changes

2024-06-05 08:17 UTC, jefim commented on Templates/CRMs/Salesforce/Generic JSON Order File to Salesforce/assets/Generic_JSON_Order_File_to_Salesforce.svg
1. Make sure to use normal casing across the process. E.g. "Read File from local fileshare" for some reason has File written with a capital F, same goes for some if statements etc.
2. In "Throw error if file was not read successfully" for some reason you give a very generic error content - can you specify that the error is that the file is empty.
3. Also, you can use "strirng.IsNullOrWhiteSpace" instead of "IsNullOrEmpty"
4. You actually use WhiteSpace for FTP and Empty for file :)
5. Same comment like in no.3 - specify the error better inside the SFTP error thing
6. Use C# string interpolation instead of String.Format. So when adding exceptions you could just write `exceptions += $"some new error {#var.something}"`.

2024-06-05 08:17 UTC, jefim commented on Templates/CRMs/Salesforce/Generic JSON Order File to Salesforce/long-description.md
> +- The Salesforce user should have access to client ID, secret and security token.
Do we have some assumptions about what data should be there in SF already?

2024-06-06 06:19 UTC, jefim approved these changes

2024-06-06 06:19 UTC, merged